server:
  port: 8084

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/order-service
    username: postgres
    password: 123456789

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true
      database: postresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect



