server:
  port: 8083

spring:
  application:
    name: Product-Service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-service


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka
